### ISSUE TITLE
RedisConnectionPoolService is missing overrides causing infinite recurrsion

### ISSUE THREAD

**Issue by leogdion** [hummingbird-project/hummingbird-redis#26]

**Comment by adam-fowler** [comment]
It is weird that RedisClient provides defaults that cause infinite recursion

**Comment by adam-fowler** [comment]
Fixed in #27

**Comment by leogdion** [comment]
Is that purposeful? 🤷

**Comment by adam-fowler** [comment]
I think i get why they were added. They allow for default parameters. Not the best way to go about it though.

**Comment by adam-fowler** [comment]
This is now released
